### ISSUE TITLE
Error with multiple answer buttons for bots.

### ISSUE THREAD

**Issue by ayarrus** [Barina/Dark-Telegram#12]
**Bot example for test:** @TempMailBot

**Images**
![image](https://user-images.githubusercontent.com/10744797/99467831-f53ae480-291d-11eb-9341-407ddc75070f.png)

**Comment by Barina** [comment]
Thanks for submitting this issue.
TBH I'm not really using Telegram for bots so I'm not very familiar with them
From the picture I can assume the issue is with the message composer textarea that is messed up
I'll try to get a complete opinion on that issue so I'll play around with that specific bot I already saw untouched elements that needs some treatment :)
Feel free to elaborate further 

PS
I've labeled this issue as enhancement as this area wasn't being addressed when I was porting the style

**Comment by Barina** [comment]
I've added some fixes towards this issue.
Can you confirm?

I've tested it on FireFox:
![image](https://user-images.githubusercontent.com/370379/99572450-5a094400-29dd-11eb-84f8-108105c956ea.png)

And on Chrome:
![image](https://user-images.githubusercontent.com/370379/99572359-347c3a80-29dd-11eb-841a-0986c92f9572.png)

**Comment by ayarrus** [comment]
nice job! only rest the voice button, idk why but i tried on all browsers and looks like this

![image](https://user-images.githubusercontent.com/10744797/99603165-8626c400-29e1-11eb-9239-f24183afa28b.png)

**Comment by Barina** [comment]
Yea this is weird.. 
I think I know what's the problem here but unfortunately I won't have access to my PC for today to check it..
The width of that area is "hard coded" so when the send button got bigger (because of language) it pushes other things away
I changed the button content to something long to confirm this
![image](https://user-images.githubusercontent.com/370379/99672953-cd15c780-2a7c-11eb-802f-4b467a7a019e.png)

**Comment by Barina** [comment]
Alright I've changed 2 lines and added 1 more and now it supposed to work as it should
FF:
![image](https://user-images.githubusercontent.com/370379/99734521-974bff80-2acb-11eb-94fc-8e93b6b85529.png)

**Comment by ayarrus** [comment]
![image](https://user-images.githubusercontent.com/10744797/99761102-06c5ed00-2ad4-11eb-9600-384cb415460f.png)

niceee job, really fast, ty for ur support! =D

**Comment by Barina** [comment]
No problem :) thank you for letting me know
