### ISSUE TITLE
Trying to import style in Safari using Cascadea does not work.

### ISSUE THREAD

**Issue by prakharb5** [Barina/Dark-Telegram#17]
I have imported several stylus themes (Dark-Whatsapp by vednoc, Github-Dark, etc.) and they all worked smoothly. 

Apparently, doing same with this theme does not work.

For e.g
I click install with stylus link in github repo of Github-Dark theme (https://github.com/StylishThemes/GitHub-Dark) and it triggers app Cascadea and it is installed successfully by app.

Now I do same with Dark-Telegram theme. It triggers the app on clicking install with stylus, but the app does not import it.

It would be very helpful if you can see why this is happening and fix it😄.

**Comment by Barina** [comment]
Interesting.
I can't do testings on safari or cascadea because of reasons 😅
But after looking on the install buttons (those are just links) I see a difference on the github-dark repo they're using the user.css extension and here we're using user.styl
So the install buttons here is just a link to:
https://raw.githubusercontent.com/Barina/Dark-Telegram/master/Dark-Telegram.user.styl
Can you try the following link to check differences? (just changed "styl" to "css"
https://raw.githubusercontent.com/Barina/Dark-Telegram/master/Dark-Telegram.user.css

If that's the case we just need to add another button here :)

**Comment by prakharb5** [comment]
Hmm, I tried, but it still did not work. Triggers the app, but is not installed into app :/

BTW, are you on Telegram or Discord? So that we can work out our issue :)

**Comment by Barina** [comment]
I don't think it's our issue (and by "our" I mean a Dark-Telegram style issue) you literally have the style file it should work.. maybe the issue is in that cascadea thing or how they process things
Maybe our friends at the GitHub-Dark know better but I didn't see anything particular in their css file
Did you also tried to use the [compiled version](https://github.com/Barina/Dark-Telegram/blob/master/darkmode.css)?
Also, can you post here a working link? just to be sure..

I've created a channel for this project in telegram (seems appropriate) we can further discuss [there](https://t.me/darktelegramstylus) :)
Although for the sake of consistency we should discuss "issue related" stuff here to prevent a mess ;)

BTW Sorry for the long delays I have less time lately (working on big project)

**Comment by mikefreuden** [comment]
Hey there! I'm actually the developer of Cascadea, and I believe this was a bug on my end. Cascadea 2.1 is now out on the App Store with some bugfixes, and this style should now work properly - please let me know if you still have issues.

**Comment by prakharb5** [comment]
O.O
Thanks mate! Will update my app ASAP!

**Comment by Barina** [comment]
> Hey there! I'm actually the developer of Cascadea, and I believe this was a bug on my end. Cascadea 2.1 is now out on the App Store with some bugfixes, and this style should now work properly - please let me know if you still have issues.

That's awesome thanks!

**Comment by prakharb5** [comment]
> I've created a channel for this project in telegram (seems appropriate) we can further discuss there :)
Although for the sake of consistency we should discuss "issue related" stuff here to prevent a mess ;)

@Barina 
What you actually created is a read-only channel, not a group. Only you can post stuff there 😄

I would suggest to delete that channel and create a group :)

**Comment by Barina** [comment]
> @Barina
> What you actually created is a read-only channel, not a group. Only you can post stuff there 😄
> 
> I would suggest to delete that channel and create a group :)

LMAO of coarse I did that 😂🤦‍♂️ I didn't want a channel I wanted a supergroup.. I'll update in a moment lol
Edit: [Link to supergroup](https://t.me/joinchat/A7st42_MOlo4MTE0)
